# Generated by Django 5.2 on 2025-04-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=100)),
                ('nome_jogador', models.CharField(max_length=100)),
                ('forca', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('constituicao', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('sabedoria', models.IntegerField()),
                ('carisma', models.IntegerField()),
                ('pontos_vida', models.IntegerField()),
                ('pontos_mana', models.IntegerField()),
                ('defesa', models.IntegerField()),
                ('classe', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
            ],
        ),
    ]
